/Artix
protocol: linux
path: uuid(eb1b355d-7b6d-4dd4-a8cc-777407cb13ad)://boot/vmlinuz-linux
module_path: uuid(eb1b355d-7b6d-4dd4-a8cc-777407cb13ad)://boot/initramfs-linux.img
cmdline: root=UUID=eb1b355d-7b6d-4dd4-a8cc-777407cb13ad rw
