-- Generated by Noctalia

primary = "rgb(cba6f7)"
surface = "rgb(1e1e2e)"
on_surface = "rgb(cdd6f4)"
secondary = "rgb(fab387)"
on_secondary = "rgb(11111b)"
error = "rgb(f38ba8)"
on_error = "rgb(11111b)"

function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = error,
        on_error = on_error,
    },
    apply_theme = apply_theme
}
